=== Subaru-PFS/drp_1d/pylibamazed/auxdir/pylibamazed/jsonschema/general.json
{
    "$id": "general",
    "$schema": "https://json-schema.org/draft/2020-12/schema",
    "title": "General",
    "type": "object",
    "required": [
        "multiobsmethod",
        "lambdarange",
        "extremaredshiftseparation",
        "smoothWidth",
        "autocorrectinput",
        "objects",
        "LSF"
    ],
    "additionalProperties": false,
    "properties": {
        "calibrationDir": {
            "description": "To be removed"
        },
        "multiobsmethod": {
            "type": "string",
            "title": "Multi obs method",
            "enum": ["", "full", "merge"],
            "description": "\n * **\"\"**: no multiobs \n * **\"full\"**: giving one spectra by observation to the lib \n * **\"merge\"**: merge observations in a single spectra"
        },
        "star": {
            "$ref": "objects.json"
        },
        "galaxy": {
            "$ref": "objects.json"
        },
        "qso": {
            "$ref": "objects.json"
        },
        "sn": {
            "$ref": "objects.json"
        },
        "lambdarange": {
            "type": ["array", "object"],
            "title": "Lambda range in Angstroms. Is a array (range) for mono obs, and a dictionary of ranges for multiobs",
            "minItems": 2,
            "maxItems": 2,
            "prefixItems": [
                {"type": "number"},
                {"type": "number"}
            ],
            "items": false
        },
        "airvacuum_method": {
            "type": "string",
            "enum": ["", "default", "Morton2000", "Edlen1953", "Edlen1966", "Peckreeder1972", "Ciddor1996"],
            "title": "Air vaccum method",
            "description": "Method to apply for the air to vacuum wavelength conversion when reading input spectrum. Currently \"default\" method corresponds to Morton2000"
        },
        "extremaredshiftseparation": {
            "type": "number",
            "title": "Extrema redshift separation",
            "description": "Minimal distance between two extrema (currently not used with linemodel)"
        },
        "smoothWidth": {
            "type": "number",
            "title": "smooth width",
            "description": "Number of elements over which to apply spectrum continuum smoothing (half kernel width)."
        },
        "autocorrectinput": {
            "type": "boolean",
            "title": "Wether to correct input spectrum",
            "description": "Wether to apply a flux/noise correction on input spectrum"
        },
        "objects": {
            "type": "array",
            "title": "List of objects to process. All mentioned objects must have dedicated section.",
            "items": {
                "type": "string"
            }
        },
        "photometryTransmissionDir": {
            "type": "string",
            "title": "Photometry transmission directory",
            "description": "Path containing the photometric transmission bands (one per file). If relative, path is relative to calibration directory. Mandatory if enablePhotometry is set to True. Raises a warning if present but enablePhotometry is set to False."
        },
        "photometryBand": {
            "type": "array",
            "title": "Photometry band",
            "description": "List of the band names to use. The name is contained in each band file, and should have the same name than the photometric data contained in the input spectra",
            "items": {
                "type": "string"
            }
        },
        "filters": {
            "type": "array",
            "title": "Filters",
            "description": "List of filters to apply for pixel selection on spectra.\n Example: we want to select the pixels for which \n 1. flag corresponding to 8 is absent \n 2. flag corresponding to 4 is present or flag is 0 : \n [{\"key\": \"Flag\", \"instruction\": \"^\", \"value\": \"8\"}, {\"key\": \"Flag\", \"instruction\": \"0&\", \"value\": \"4\"}]",
            "items": {
                "type": "object",
                "properties": {
                    "key": {
                        "type": "string",
                        "title": "Column name",
                        "description": "Name of the spectrum column to filter on"
                    },
                    "instruction": {
                        "type": "string",
                        "enum": ["<", ">", "<=", ">=", "=", "in", "~in", "!=", "&", "0&", "^"],
                        "title": "Comparison type",
                        "description": "\n * **in**: value must the be a list of possible value \n * **~in**: not in \n * **!=**: different \n * **&**: binary and \n * **0&**: binary and or 0 \n * **^**: xor"
                    },
                    "value": {
                        "title": "Value to compare with",
                        "description": "Possible values are int - float - list of numbers (for `in` and `!in` only)"
                    }
                },
                "required": ["key", "instruction", "value"]
            }
        },
        "additional_cols": {
            "type": "array",
            "title": "Additional columns",
            "description": "List of spectrum columns to take into account addtionally to \"Wave\" \"Flux\" \"Err\". Ex: [\"Flags\"] If you want to filter incoming spectra depending on column a column named Flags",
            "items": {
                "type": "string"
            }
        },
        "LSF": {
            "type": "object",
            "title": "Line spread function",
            "$ref": "lsf.json"
        },
        "ebmv": {
            "type": "object",
            "title": "b minus v",
            "description": "b minus v: color ratio, used to calculate ISM extinction curve.",
            "$ref": "ebmv.json"
        },
        "templateCatalog": {
            "type": "object",
            "title": "Template catalog",
            "description": "",
            "$ref": "template_catalog.json"
        },
        "continuumRemoval": {
            "type": "object",
            "title": "Continuum removal",
            "description": "",
            "$ref": "continuum_removal.json"
        }
    }
}

=== Subaru-PFS/drp_1d/pylibamazed/auxdir/pylibamazed/test/p_se8_main.json
{
    "multiobsmethod": "",
    "lambdarange": [
        12510,
        18500
    ],
    "smoothWidth": 0.0,
    "templateCatalog": {
        "continuumRemoval": {
            "method": "zero",
            "medianKernelWidth": 75,
            "medianEvenReflection": true
        }
    },
    "ebmv": {
        "start": 0,
        "step": 0.1,
        "count": 10
    },
    "continuumRemoval": {
        "method": "IrregularSamplingMedian",
        "medianKernelWidth": 150,
        "medianEvenReflection": true,
        "decompScales": 9,
        "binPath": ""
    },
    "airvacuum_method":"default",
    "LSF": {
        "LSFType": "GaussianNISPVSSPSF201707",
        "sourcesize": 0.1
    },
    "extremaredshiftseparation": 0.01,
    "objects": [
        "galaxy"
    ],
    "calibrationDir": "",
    "autocorrectinput": false,
    "galaxy": {
        "redshiftrange": [
            0.9001832537307723481,
            1.70026612
        ],
        "redshiftstep": 0.0001,
        "redshiftsampling": "log",
        "method": "LineModelSolve",
        "template_dir": "templates/BC03_sdss_tremonti21",
        "LineModelSolve": {
            "linemodel": {
                "linecatalog": "linecatalogs/linecatalogamazedvacuum_H0.tsv",
                "linetypefilter": "E",
                "lineforcefilter": "no",
                "fittingmethod": "individual",
                "igmfit": false,
                "linewidthtype": "combined",
                "velocityemission": 100,
                "velocityabsorption": 100,
                "velocityfit": true,
                "pdfcombination": "marg",
                "emvelocityfitmin": 100,
                "emvelocityfitmax": 700,
                "emvelocityfitstep": 20,
                "absvelocityfitmin": 150,
                "absvelocityfitmax": 500,
                "absvelocityfitstep": 50,
                "lyaforcefit": false,
                "lyaforcedisablefit": false,
                "lyafit": {
                    "asymfitmin": 0,
                    "asymfitmax": 4,
                    "asymfitstep": 1,
                    "widthfitmin": 1,
                    "widthfitmax": 4,
                    "widthfitstep": 1,
                    "deltafitmin": 0,
                    "deltafitmax": 0,
                    "deltafitstep": 1
                },
                "extremacountB": 0,
                "haprior": -1,
                "lineRatioType": "tplratio",
                "rules": "all",
                "improveBalmerFit": true,
                "tplratio_catalog": "linecatalogs_tplshapes/linecatalogs_tplshape_ExtendedTemplatesJan2017v3_20170602_B14C_v16_emission",
                "tplratio_ismfit": true,
                "continuumcomponent": "tplfit",
                "continuumreestimation": "no",
                "continuumfit": {
                    "negativethreshold": -5.0,
                    "nullthreshold": 3,
                    "fftprocessing": false,
                    "ismfit": true,
                    "igmfit": false,
                    "count": 1,
                    "ignorelinesupport": false,
                    "priors": {
                        "betaA": 1,
                        "betaTE": 1,
                        "betaZ": 1,
                        "catalog_dirpath": ""
                    }
                },
                "useloglambdasampling": false,
                "skipsecondpass": false,
                "extremacount": 5,
                "extremacutprobathreshold": -1,
                "pdf": {
                    "margampcorr": false,
                    "bestzoption": "maxintproba"
                },
                "firstpass": {
                    "fittingmethod": "individual",
                    "largegridstepratio": 10,
                    "tplratio_ismfit": false,
                    "multiplecontinuumfit_disable": true
                },
                "secondpass": {
                    "halfwindowsize": 0.002,
                    "continuumfit": "refitfirstpass"
                },
                "secondpasslcfittingmethod": -1,
                "stronglinesprior": 0.001,
                "euclidnhaemittersStrength": -1,
                "tplratio": {
                    "priors": {
                        "betaA": 1,
                        "betaTE": 1,
                        "betaZ": 1,
                        "catalog_dirpath": ""
                    }
                },
                "nsigmasupport": 8,
                "enablephotometry": true,
                "photometry": {
                    "weight": 1.0
                }

            }
        },
        "linemeas_method": "LineMeasSolve",
        "linemeas_dzhalf": 0.001,
        "linemeas_redshiftstep": 0.0001,
        "LineMeasSolve": {
            "linemodel": {
                "continuumcomponent": "nocontinuum",
                "linecatalog": "linecatalogs/linecatalogamazedvacuum_H0.tsv",
                "linetypefilter": "E",
                "lineforcefilter": "no",
                "nsigmasupport": 8,
                "linewidthtype": "combined",
                "fittingmethod": "hybrid",
                "polynomialdegree": 2,
                "velocityfit": false,
                "lineRatioType": "rules",
                "rules": "no",
                "igmfit": false,
                "improveBalmerFit": true,
                "lyaforcedisablefit": false
            }
        },
        "enable_reliability": false,
        "reliability_model": "reliability/NNmodels/tagged/NN04181302_25_WholeModel.h5"
    },
        "photometryTransmissionDir": "photometric_transmission/EL-COSMOSv2/",
	"photometryBand": [
		"H",
		"J",
		"Y",
		"riz"
	 ]
}
